# SPDX-FileCopyrightText: 2022-2025 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[default]
extend-ignore-re = [
  ".*ssh-ed25519 .*",
  ".*aks-uaenorth.*",
  ".*set -ue.*",
  ".*https?://.*",
]

[default.extend-words]
certin = "certin"
