# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: GitHub Actions Version Updater
on:
  workflow_dispatch:
  schedule:
    # Automatically run on every Sunday at 00:00 UTC.
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}
      
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}
          pull_request_title: "Update GitHub Actions to Latest Version"